// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGoCrmUser = "go_crm_user"

// GoCrmUser mapped from table <go_crm_user>
type GoCrmUser struct {
	UsrID            int32  `gorm:"column:usr_id;primaryKey;autoIncrement:true" json:"usr_id"`
	UsrEmail         string `gorm:"column:usr_email;not null" json:"usr_email"`
	UsrPhone         string `gorm:"column:usr_phone" json:"usr_phone"`
	UsrUsername      string `gorm:"column:usr_username;not null" json:"usr_username"`
	UsrPassword      string `gorm:"column:usr_password;not null" json:"usr_password"`
	UsrCreatedAt     int32  `gorm:"column:usr_created_at;not null" json:"usr_created_at"`
	UsrUpdatedAt     int32  `gorm:"column:usr_updated_at;not null" json:"usr_updated_at"`
	UsrCreateIPAt    string `gorm:"column:usr_create_ip_at" json:"usr_create_ip_at"`
	UsrLastLoginAt   int32  `gorm:"column:usr_last_login_at;not null" json:"usr_last_login_at"`
	UsrLastLoginIPAt string `gorm:"column:usr_last_login_ip_at" json:"usr_last_login_ip_at"`
	UsrLoginTimes    int32  `gorm:"column:usr_login_times;not null" json:"usr_login_times"`
	UsrStatus        bool   `gorm:"column:usr_status;not null" json:"usr_status"`
}

// TableName GoCrmUser's table name
func (*GoCrmUser) TableName() string {
	return TableNameGoCrmUser
}
